import {
  DebitNotesSvg,
  HoldingPoSvg,
  UnDelvPoSvg,
  UnpaidInvsSvg,
} from "../icons/CommonDashboardSvg";
import { PDFFileSvg } from "../icons/CommonPurchaseOrderSvg";
import {
  SideBarHomeSvg,
  SideBarInventorySvg,
  SideBarInvoicesSvg,
  SideBarLogisticsSvg,
  SideBarMBQSvg,
  SideBarNotificationsSvg,
  SideBarPurchaseOrderSvg,
  SideBarSettingsSvg,
} from "../icons/SideBarSvgs";

export const initialData = [
  {
    id: 1,
    logisticNo: "LOG/L5",
    date: "01/01/25",
    transporter: "VRL",
    parcels: 2,
    quantity: 500,
    poNo: "L23",
    delivered: "No",
    status: "Completed",
  },
  {
    id: 2,
    logisticNo: "LOG/L5",
    date: "01/01/25",
    transporter: "VRL",
    parcels: 2,
    quantity: 500,
    poNo: "L23",
    delivered: "No",
    status: "Cancel",
  },
  {
    id: 3,
    logisticNo: "LOG/L5",
    date: "01/01/25",
    transporter: "VRL",
    parcels: 2,
    quantity: 500,
    poNo: "L23",
    delivered: "No",
    status: "In Progress",
  },
  {
    id: 4,
    logisticNo: "LOG/L5",
    date: "01/01/25",
    transporter: "VRL",
    parcels: 2,
    quantity: 500,
    poNo: "L23",
    delivered: "No",
    status: "Completed",
  },
  {
    id: 5,
    logisticNo: "LOG/L5",
    date: "01/01/25",
    transporter: "VRL",
    parcels: 2,
    quantity: 500,
    poNo: "L23",
    delivered: "No",
    status: "Cancel",
  },
  {
    id: 6,
    logisticNo: "LOG/L5",
    date: "01/01/25",
    transporter: "VRL",
    parcels: 2,
    quantity: 500,
    poNo: "L23",
    delivered: "No",
    status: "In Progress",
  },
  {
    id: 7,
    logisticNo: "LOG/L5",
    date: "01/01/25",
    transporter: "VRL",
    parcels: 2,
    quantity: 500,
    poNo: "L23",
    delivered: "No",
    status: "Completed",
  },
];

export const cardData = [
  {
    title: "Holding POs",
    count: 2,
    icon: <HoldingPoSvg />,
    iconColor: "text-indigo-500",
    bgColor: "bg-partyparrot",
  },
  {
    title: "UnDelv POs",
    count: 3,
    icon: <UnDelvPoSvg />,
    iconColor: "text-orange-500",
    bgColor: "bg-ginger",
  },
  {
    title: "Debit Notes",
    count: 4,
    icon: <DebitNotesSvg />,
    iconColor: "text-green-500",
    bgColor: "bg-chelsea",
  },
  {
    title: "Unpaid Invs",
    count: 2,
    icon: <UnpaidInvsSvg />,
    iconColor: "text-blue-500",
    bgColor: "bg-brandeis",
  },
];

export const invoices = [
  {
    id: 1,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
  {
    id: 2,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
  {
    id: 3,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
  {
    id: 4,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
  {
    id: 5,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
  {
    id: 6,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
  {
    id: 7,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
  {
    id: 8,
    po: "L23",
    date: "01/01/25",
    agent: "JK Enterprise",
    items: "Saree",
    quantity: "500",
    rcvd: "0",
    pend: "500",
    amount: "156700",
    delivered: "No",
    sent: "No",
  },
];

export const data = [
  {
    invNo: "INV/L5",
    date: "01/01/25",
    invoice: "23/2024",
    poDate: "09/May/24",
    poNo: "L23",
    qty: 500,
    retSh: 0,
    net: 500,
    invAmt: "1,34,00",
    paid: "No",
    stock: 350,
  },
  {
    invNo: "INV/L5",
    date: "01/01/25",
    invoice: "23/2024",
    poDate: "09/May/24",
    poNo: "L23",
    qty: 500,
    retSh: 0,
    net: 500,
    invAmt: "1,34,00",
    paid: "No",
    stock: 350,
  },
  {
    invNo: "INV/L5",
    date: "01/01/25",
    invoice: "23/2024",
    poDate: "09/May/24",
    poNo: "L23",
    qty: 500,
    retSh: 0,
    net: 500,
    invAmt: "1,34,00",
    paid: "No",
    stock: 350,
  },
  {
    invNo: "INV/L5",
    date: "01/01/25",
    invoice: "23/2024",
    poDate: "09/May/24",
    poNo: "L23",
    qty: 500,
    retSh: 0,
    net: 500,
    invAmt: "1,34,00",
    paid: "No",
    stock: 350,
  },
  {
    invNo: "INV/L5",
    date: "01/01/25",
    invoice: "23/2024",
    poDate: "09/May/24",
    poNo: "L23",
    qty: 500,
    retSh: 0,
    net: 500,
    invAmt: "1,34,00",
    paid: "No",
    stock: 350,
  },
  {
    invNo: "INV/L5",
    date: "01/01/25",
    invoice: "23/2024",
    poDate: "09/May/24",
    poNo: "L23",
    qty: 500,
    retSh: 0,
    net: 500,
    invAmt: "1,34,00",
    paid: "No",
    stock: 350,
  },
  {
    invNo: "INV/L5",
    date: "01/01/25",
    invoice: "23/2024",
    poDate: "09/May/24",
    poNo: "L23",
    qty: 500,
    retSh: 0,
    net: 500,
    invAmt: "1,34,00",
    paid: "No",
    stock: 350,
  },
];

export const menuItems = [
  {
    name: "Dashboard",
    path: "/dashboard",
    icon: <SideBarHomeSvg />,
  },
  {
    name: "Purchase Orders",
    path: "/purchase-orders",
    icon: <SideBarPurchaseOrderSvg />,
  },
  {
    name: "Logistics",
    path: "/logistics",
    icon: <SideBarLogisticsSvg />,
  },
  {
    name: "Invoices",
    path: "/invoices-list",
    icon: <SideBarInvoicesSvg />,
  },
  {
    name: "Inventory",
    path: "/inventory",
    icon: <SideBarInventorySvg />,
  },
  {
    name: "MBQ",
    path: "/mbq",
    icon: <SideBarMBQSvg />,
  },
  {
    name: "Notifications ",
    path: "/notifications",
    icon: <SideBarNotificationsSvg />,
  },
  {
    name: "Settings",
    path: "/settings",
    icon: <SideBarSettingsSvg />,
  },
];

export const viewsData = {
  // commodore  views
  productview: {
    title: "By Product",
    tableHeaders: ["Description", "Quantity", "Value"],
    tableData: [
      ["Saree", "50", "35,000"],
      ["Work Saree", "65", "45,000"],
      ["Benaras Saree", "45", "75,000"],
    ],
    filterOptions: ["invoiceview", "ageslabview", "priceslabview", "groupview"],
  },
  invoiceview: {
    title: "By Invoice",
    tableHeaders: ["Invoice No.", "Invoice Date", "Quantity", "Value"],
    tableData: [
      ["INV/50", "10-2-2025", "50", "35,000"],
      ["INV/40", "10-2-2025", "65", "45,000"],
      ["INV/56", "10-2-2025", "45", "75,000"],
    ],
    filterOptions: ["productview", "ageslabview", "priceslabview", "groupview"],
  },
  ageslabview: {
    title: "By Age Slab",
    tableHeaders: ["Age Slab", "Quantity", "Value"],
    tableData: [
      ["0-30 Days", "50", "35,000"],
      ["31-60 Days", "65", "45,000"],
      ["61-90 Days", "45", "75,000"],
    ],
    filterOptions: ["productview", "invoiceview", "priceslabview", "groupview"],
  },
  priceslabview: {
    title: "By Price Slab",
    tableHeaders: ["Price Range", "Quantity", "Value"],
    tableData: [
      ["₹0 - ₹500", "50", "35,000"],
      ["₹500 - ₹1,000", "65", "45,000"],
      ["₹1,000 - ₹2,000", "45", "75,000"],
    ],
    filterOptions: ["productview", "invoiceview", "ageslabview", "groupview"],
  },
  groupview: {
    title: "By Group",
    tableHeaders: ["Group", "Quantity", "Value"],
    tableData: [
      ["Group A", "50", "35,000"],
      ["Group B", "65", "45,000"],
      ["Group C", "45", "75,000"],
    ],
    filterOptions: [
      "productview",
      "invoiceview",
      "ageslabview",
      "priceslabview",
    ],
  },

  // Nested views
  productview_Saree: {
    title: "Saree Details",
    tableHeaders: ["Description", "Quantity", "Value"],
    tableData: [
      ["Plain Saree", "20", "15,000"],
      ["Printed Saree", "30", "20,000"],
    ],
    filterOptions: ["invoiceview", "ageslabview", "priceslabview", "groupview"],
  },

  "productview_Work Saree": {
    title: "Work Saree Details",
    tableHeaders: ["Description", "Quantity", "Value"],
    tableData: [
      ["Embroidery Work", "35", "25,000"],
      ["Zari Work", "30", "20,000"],
    ],
    filterOptions: ["invoiceview", "ageslabview", "priceslabview", "groupview"],
  },

  "invoiceview_Work Saree": {
    title: "By Invoice > Work Saree",
    tableHeaders: ["Invoice No.", "Invoice Date", "Quantity", "Value"],
    tableData: [
      ["INV/50", "10-2-2025", "10", "5,500"],
      ["INV/45", "18-2-2025", "35", "25,000"],
      ["INV/56", "22-2-2025", "20", "14,500"],
    ],
    filterOptions: ["productview", "ageslabview", "priceslabview", "groupview"],
  },

  "ageslabview_31-60 Days": {
    title: "By Age Slab > 31-60 Days",
    tableHeaders: ["Description", "Quantity", "Value"],
    tableData: [
      ["Saree", "20", "15,000"],
      ["Work Saree", "35", "25,000"],
      ["Benaras Saree", "10", "5,000"],
    ],
    filterOptions: ["productview", "invoiceview", "priceslabview", "groupview"],
  },

  "priceslabview_₹500 - ₹1,000": {
    title: "By Price Slab > ₹500 - ₹1,000",
    tableHeaders: ["Description", "Quantity", "Value"],
    tableData: [
      ["Saree", "25", "21,000"],
      ["Work Saree", "30", "27,000"],
      ["Benaras Saree", "10", "8,000"],
    ],
    filterOptions: ["productview", "invoiceview", "ageslabview", "groupview"],
  },
};

export const mcqdata = [
  {
    product: "Shirts",
    brand: "Twills",
    priceSlab: "Upto 5K",
    color: "-",
    design: "-",
    inStock: 75,
    min: 50,
    max: 100,
    status: "-",
  },
  {
    product: "Shirts",
    brand: "Twills",
    priceSlab: "Upto 5K",
    color: "-",
    design: "-",
    inStock: 75,
    min: 50,
    max: 100,
    status: "-",
  },
  {
    product: "Shirts",
    brand: "Twills",
    priceSlab: "Upto 5K",
    color: "-",
    design: "-",
    inStock: 75,
    min: 50,
    max: 100,
    status: "-",
  },
  {
    product: "Shirts",
    brand: "Twills",
    priceSlab: "Upto 5K",
    color: "-",
    design: "-",
    inStock: 75,
    min: 50,
    max: 100,
    status: "-15",
  },
  {
    product: "Shirts",
    brand: "Twills",
    priceSlab: "Upto 5K",
    color: "-",
    design: "-",
    inStock: 75,
    min: 50,
    max: 100,
    status: "-",
  },
  {
    product: "Shirts",
    brand: "Twills",
    priceSlab: "Upto 5K",
    color: "-",
    design: "-",
    inStock: 75,
    min: 50,
    max: 100,
    status: "-",
  },
  {
    product: "Shirts",
    brand: "Twills",
    priceSlab: "Upto 5K",
    color: "-",
    design: "-",
    inStock: 75,
    min: 50,
    max: 100,
    status: "-",
  },
];

export const notifications = [
  {
    id: 1,
    message: "Minimum balance Crossed for T-Shirts",
    date: "14/02/05",
    isBold: true,
  },
  {
    id: 2,
    message: "Invoice No 567 was paid. Please Check",
    date: "14/02/05",
  },
  {
    id: 3,
    message:
      "Stock Returned in the Inv 345 by logistic no 77889383 VRL. Please check.",
    date: "14/02/05",
  },
  {
    id: 4,
    message: "Invoice No 567 was paid. Please Check",
    date: "14/02/05",
  },
  {
    id: 5,
    message:
      "Stock Returned in the Inv 345 by logistic no 77889383 VRL. Please check.",
    date: "14/02/05",
  },
];
